[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

# SPA redirect rule - this is crucial for React Router to work
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/whatsapp-webhook"
  to = "/.netlify/functions/whatsapp-webhook"
  status = 200

[[redirects]]
  from = "/api/test-webhook"
  to = "/.netlify/functions/test-webhook"
  status = 200

[[redirects]]
  from = "/api/whatsapp-official-webhook"
  to = "/.netlify/functions/whatsapp-official-webhook"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/api/whatsapp-proxy"
  to = "/.netlify/functions/whatsapp-proxy"
  status = 200

[[redirects]]
  from = "/api/green-api-proxy"
  to = "/.netlify/functions/green-api-proxy"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"

