[build]
  command = "echo Skipping build"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  timeout = 30

[[redirects]]
  from = "/api/whatsapp-webhook"
  to = "/.netlify/functions/whatsapp-webhook"
  status = 200
  force = true

[[headers]]
  for = "/.netlify/functions/whatsapp-webhook"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "preview"

[context.branch-deploy.environment]
  NODE_ENV = "development"

